# Generated by Django 4.1.7 on 2024-02-25 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_userhistoryviewproduct_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistoryviewproduct',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 11, 24, 18, 255110, tzinfo=datetime.timezone.utc)),
        ),
    ]
