# Generated by Django 4.1.7 on 2024-02-29 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_userhistoryviewproduct_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.vendor', verbose_name='Vendor'),
        ),
        migrations.AlterField(
            model_name='userhistoryviewproduct',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 6, 1, 11, 898540, tzinfo=datetime.timezone.utc)),
        ),
    ]
