# Generated by Django 4.1.7 on 2024-02-29 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_vender_alter_userhistoryviewproduct_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistoryviewproduct',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 6, 7, 23, 181358, tzinfo=datetime.timezone.utc)),
        ),
    ]
