# Generated by Django 4.1.7 on 2024-02-29 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_userhistoryviewproduct_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vender',
            new_name='vendor',
        ),
        migrations.AlterField(
            model_name='userhistoryviewproduct',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 6, 7, 41, 338284, tzinfo=datetime.timezone.utc)),
        ),
    ]
